config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # post "users", to: "users#create"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 25, maximum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :article, dependent: :destroy
	validates :username, presence: true, 
							length: {minimum: 3, maximum: 25}, 
							uniqueness: {case_sensitive: false}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
						length: {maximum: 100}, 
						uniqueness: {case_sensitive: false},
						format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:alert] = "Please Login To Access This Page"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:show,:edit,:update,:destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit,:update,:destroy]

	def show
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Article was created successfully."
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article was updated successfully."
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end

	def require_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:alert] = "You can only edit/delete your own Artiles"
			redirect_to @article
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end

	def about
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "Logged In Successfully"
			redirect_to user
		else
			flash.now[:alert] = "Please check the credentials"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged Out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index, :new, :create]
	before_action :require_same_user, only: [:edit,:update,:destroy]

	def show
		@articles = @user.article
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end

	def new
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "User information was updated successfully."
			redirect_to @user
		else
			render 'edit'
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Welcome to the Kavin-Blog"
			redirect_to @user
		else
			render 'new'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:notice] = "Account and all associated articles has been deleted!"
		redirect_to articles_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user && !current_user.admin?
			flash[:alert] = "You can only edit/delete your own Account"
			redirect_to @user
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, option = {size: 80})
		email_address = user.email;
		hash = Digest::MD5.hexdigest(email_address)
		size = option[:size]
		url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(url, alt: user.username, class: "rounded mx-auto d-block shadow")
	end
end

app/views/articles/_articles.html.erb
<table border="1" class="text-center mx-auto table table-bordered table-hover" style="width: 75%;">
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>By</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.description %></td>
			<td><%= if article.user 
					 link_to article.user.username, user_path(article.user)
					end %></td>
			<td><%= link_to 'Show', article_path(article), class: "btn btn-info" %></td>
			<td>
				<% if logged_in? && (article.user == current_user || current_user.admin?) %>
					<%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %>
				<% end %>
			</td>
			<td>
				<% if logged_in? && (article.user == current_user || current_user.admin?) %>
					<%= link_to 'Delete', article_path(article), method: :delete,  data: { confirm: "Are You Sure?" }, class: "btn btn-danger" %></td>
				<% end %>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any?  %>
	<h3>The following errors prevented saving the data</h3>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>
<div>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description, rows: "10" %>
	</p>

	<p>
		<%= f.submit %> 
	</p>
</div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
	<h1 class="text-center">Edit Article</h1>

	<%= render 'form' %>

	<p>
		<%= link_to 'Cancel & Return', articles_path, class: "btn btn-primary" %>
	</p>
</div>

app/views/articles/index.html.erb
<h1 class="text-center">Article Listing</h1>
<%= render "articles" %>
<br>
<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<% if logged_in? &&  %>
	<p class="text-center">
		<%= link_to "Create New Article", new_article_path, class: "btn btn-primary" %>
	</p>
<% end %>

app/views/articles/new.html.erb
<div class="container">
	<h1 class="text-center">Create New Article</h1>

	<%= render 'form' %>

	<p>
		<%= link_to 'Return', articles_path, class: "btn btn-primary" %>
	</p>
</div>

app/views/articles/show.html.erb
<div class="container">
	<h1 class="text-center">Article</h1>

	<div class="text-left">
		<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
		<div class="w-50 mx-auto">
			<p><strong>Title : </strong><%= @article.title %></p>
			<p><strong>Description : </strong><%= @article.description %></p>
			<p><strong>Created By : </strong><%= @article.user.username if @article.user %><small> (<%= time_ago_in_words(@article.created_at) %> ago)</small></p>

			<p>
				<% if logged_in? && (@article.user == current_user || current_user.admin? ) %>
					<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-warning" %>
					<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are You Sure?" } , class: "btn btn-danger" %>
				<% end %>
				<%= link_to 'Return', articles_path , class: "btn btn-primary" %>
			</p>
		</div>
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <div class="text-center w-50 mx-auto alert alert-<%= name == 'notice' ? 'success' : 'danger' %>">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

    </div> 
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Kavin Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? &&  %>
            <li>
              <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
            </li>
            <% end %>
            <li>
              <%= link_to "View Article", articles_path, class: "dropdown-item" %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        
        <!-- <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> -->
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
      <div>
        <div class="nav-item navbar-nav">
          <% if logged_in? %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %><%= "(Admin)" if current_user.admin? %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                </li>
                <li>
                  <%= link_to 'Delete Profile', user_path(current_user), class: "dropdown-item text-danger" ,
                method: :delete, data: {confirm: "Are you sure?"} %>
                </li>
                <li>
                  <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete %>
                </li>
              </ul>
            </div>
          <% else %>
            <div class="nav-item">
              <%= link_to "Login", login_path, class: "nav-link" %>
            </div>
            <div class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KavinBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">Welcome to about</h1>

<%= link_to 'Articles', articles_path , class: "btn btn-success" %>

<%= link_to 'Home', root_path, class: "btn btn-warning" %>

app/views/pages/home.html.erb
<div class="container">
	<div class="home_page">
		<div class="jumbotron">
		  <h1 class="display-4 text-center">Kavin Blog</h1>
		  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		  <hr class="my-4">
		  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		  <p class="lead text-center">
		    <%= link_to 'Articles', articles_path, class: "btn btn-success btn-lg" %>
		    <%= link_to 'Sign Up', signup_path, class: "btn btn-primary btn-lg" %>
		  </p>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any?  %>
	<h3>The following errors prevented saving the data</h3>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<div>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field :username , class: "form-control rounded shadow w-50", placeholde:"Enter Username" %>
	</p>

	<p>
		<%= f.label :email %><br>
		<%= f.email_field :email , class: "form-control rounded shadow w-50", placeholde:"Enter Email" %>
	</p>

	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password, class: "form-control rounded shadow w-50", placeholde:"Enter Password" %>
	</p>

	<p>
		<%= f.submit %> 
	</p>
</div>

<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1 class="text-center">Edit User</h1>

	<%= render 'form' %>

	<p>
		<%= link_to 'Return', users_path, class: "btn btn-primary" %>
	</p>
</div>

app/views/users/index.html.erb
<h1 class="text-center">Kavin Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.article.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? && (user == current_user || current_user.admin?) %>
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            <% if logged_in? && current_user.admin? && !user.admin? %>
              <%= link_to 'Delete Profile', user_path(user), class: "btn btn-danger" ,
                method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="apple_pagination">
      <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1 class="text-center">Create New User</h1>

	<%= render 'form' %>

	<p>
		<%= link_to 'Return', users_path, class: "btn btn-primary" %>
	</p>
</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 200 %><br>

<div class="text-center mt-4">
	<% if logged_in? && (@user == current_user || current_user.admin?) %>
		<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-info" %>
	<% end %>
	<% if logged_in? && current_user.admin? && !@user.admin? %>
      <%= link_to 'Delete Profile', user_path(@user), class: "btn btn-danger" ,
        method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
</div>
<br>
<h3 class="text-center">Articles By <%= @user.username %></h3>

<%= render "articles/articles" %>